spring:
  main:
    banner-mode: off
    allow-circular-references: true
  application:
    name: core
  profiles:
    active: dev

url:
  core: https://0a78-118-70-132-104.ngrok-free.app/cam
  website: https://daotao.vnua.edu.vn/Default.aspx?page=thoikhoabieu&sta=1&id=

jwt:
  secret: 8734657346587346587346587346587345

#logging:
#  file:
#    path: /static/
#    name: test.log
#  level:
#    root: error
